# These are supported funding model platforms

github: # Replace with GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: zquestdevs
custom: # Replace with custom sponsorship URLs e.g., ['link1', 'link2']
