// See docs/protocol.md

#ifndef _ZQ_PROTOCOL_H_
#define _ZQ_PROTOCOL_H_

#include "zq/protocol/impl.h"
#include <string>
#include "json/json.h"

using giri::json::JSON;

void protocol_server_start();
void protocol_server_poll();
void protocol_broadcast_event(protocol::events::type type, JSON& params_json);

// The following are generated by `scripts/generate_protocol.py` and are defined in `impl.cpp`.
protocol::commands::type protocol_parse_command(std::string command);
std::string protocol_event_to_string(protocol::events::type type);
JSON protocol_handle_command(protocol::commands::type type, JSON& params_json);

#endif
