name: CI

on:
  push:
    # branches: [2.55-master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  compile-windows:
    runs-on: windows-latest

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win32

    - name: git clone
      uses: actions/checkout@v2

    - name: Install Dependencies
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install .github/dependencies.config -y

    - run: cp src/metadata/*.h.sig src/metadata/sigs/
    - run: cmake . -A win32
    - run: cmake --build . --config Release --verbose --target zquest
    - run: cmake --build . --config Release --verbose --target zelda
    - run: cmake --build . --config Release --verbose --target zlauncher

  compile-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: git clone
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install flex bison libxcursor-dev libasound2-dev gcc-multilib g++-multilib libglu1-mesa-dev freeglut3-dev mesa-common-dev

    - run: cp src/metadata/*.h.sig src/metadata/sigs/
    - run: cmake . -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build . --verbose --target zquest
    - run: cmake --build . --verbose --target zelda
    - run: cmake --build . --verbose --target zlauncher
