name: CI

on:
  push:
  pull_request:

jobs:
  compile-windows:
    runs-on: windows-2022

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win32

    - name: git clone
      uses: actions/checkout@v2

    - name: Install Dependencies
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install .github/dependencies.config -y

    - run: cp src/metadata/*.h.sig src/metadata/sigs/
    - run: cmake . -A win32

    # Build things individually just to have some seperation in the GHA UI.
    - run: cmake --build . --config Release --target zcsound
    - run: cmake --build . --config Release --target zquest
    - run: cmake --build . --config Release --target zelda
    - run: cmake --build . --config Release --target zscript
    - run: cmake --build . --config Release --target zlauncher

    # Build anything else that may not be covered above.
    - run: cmake --build . --config Release

  compile-mac:
    runs-on: macos-12

    steps:
    - name: git clone
      uses: actions/checkout@v2
    
    - run: brew install ninja
    - name: Install Bison
      run: |
        wget http://ftp.gnu.org/gnu/bison/bison-3.6.tar.gz
        tar -zxvf bison-3.6.tar.gz
        cd bison-3.6
        ./configure
        make
        sudo make install

    - run: cp src/metadata/*.h.sig src/metadata/sigs/
    - run: cmake -G Ninja .

    # Build things individually just to have some seperation in the GHA UI.
    - run: cmake --build . --target zcsound
    - run: cmake --build . --target zquest
    - run: cmake --build . --target zelda
    - run: cmake --build . --target zscript
    - run: cmake --build . --target zlauncher

    # Build anything else that may not be covered above.
    - run: cmake --build .
