name: CI

on:
  push:
  pull_request:

jobs:
  compile:
    runs-on: windows-2022

    steps:
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: win32

    - name: git clone
      uses: actions/checkout@v2

    - name: Install Dependencies
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install .github/dependencies.config -y

    - run: cp src/metadata/*.h.sig src/metadata/sigs/
    - run: cmake . -A win32

    # Build things individually just to have some seperation in the GHA UI.
    - run: cmake --build . --config Release --target zcsound
    - run: cmake --build . --config Release --target zquest
    - run: cmake --build . --config Release --target zelda
    - run: cmake --build . --config Release --target zscript
    - run: cmake --build . --config Release --target zlauncher

    # Build anything else that may not be covered above.
    - run: cmake --build . --config Release
