name: Release Cron

on:
  schedule:
    # Once a week at midnight EST on saturday.
    - cron: '0 4 * * 6'

jobs:
  check-date:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run_cron.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run_cron
        continue-on-error: true
        if: github.event_name == 'schedule' && github.event.pull_request.head.repo.full_name == 'ArmageddonGames/ZQuestClassic'
        run: test -z $(git rev-list --after="1 week" ${{ github.sha }}) || echo "::set-output name=should_run::true"

  scheduled-release:
    needs: ["check-date"]
    if: ${{ needs.check-date.outputs.should_run == 'true' }}
    # See https://github.com/community/community/discussions/40777
    # uses: ./.github/workflows/release.yml
    uses: ArmageddonGames/ZQuestClassic/.github/workflows/release.yml@main
