name: Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        type: choice
        description: New stable release or nightly?
        options:
          - stable
          - nightly
        required: true
        default: nightly
      sentry:
        type: boolean
        description: Perform a sentry release
        default: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.make-vars.outputs.release-tag }}
      release-name: ${{ steps.make-vars.outputs.release-name }}
      previous-release-tag: ${{ steps.make-vars.outputs.previous-release-tag }}
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags
      - id: make-vars
        run: |
          python3 .github/workflows/print-release-name-vars.py \
            --github_org=${{ github.repository_owner }} \
            --version_type=${{ github.event.inputs.version-type }}

      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1.3.0
        if: inputs.sentry
        with:
          version: '2.20.6'
          token: ${{ secrets.SENTRY_TOKEN }}
          organization: zeldaclassic
          project: zc-test
      - run: sentry-cli --version
        if: inputs.sentry
      - run: sentry-cli --log-level=DEBUG releases new 'zc-test@${{ steps.make-vars.outputs.release-tag }}'
        if: inputs.sentry

  build-release:
    needs: ["create-tag"]
    strategy:
      matrix:
        include:
          - runs-on: windows-2022
            arch: x64
            compiler: msvc
            config: RelWithDebInfo
            sentry: ${{ inputs.sentry }}
          - runs-on: windows-2022
            arch: win32
            compiler: msvc
            config: RelWithDebInfo
            sentry: ${{ inputs.sentry }}
          - runs-on: macos-12
            arch: intel
            compiler: clang
            config: RelWithDebInfo
            sentry: ${{ inputs.sentry }}
          - runs-on: ubuntu-22.04
            arch: x64
            compiler: clang
            config: RelWithDebInfo
            sentry: ${{ inputs.sentry }}
      fail-fast: false
    # See https://github.com/community/community/discussions/40777
    uses: ./.github/workflows/build.yml
    # uses: ZQuestClassic/ZQuestClassic/.github/workflows/build.yml@main
    with:
      runs-on: ${{ matrix.runs-on }}
      arch: ${{ matrix.arch }}
      compiler: ${{ matrix.compiler }}
      config: ${{ matrix.config }}
      sentry: ${{ matrix.sentry }}
      release-tag: ${{ needs.create-tag.outputs.release-tag }}
      release-name: ${{ needs.create-tag.outputs.release-name }}
      cache: false
      number: ${{ inputs.number }}
      versiontype: ${{ inputs.versiontype }}
      full_release: ${{ inputs.full_release }}
    secrets: inherit

  publish:
    needs:
      - create-tag
      - build-release
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    steps:
      - name: git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          path: release-packages

      - name: Generate changelog
        run: python scripts/generate_changelog.py --format markdown --from ${{ needs.create-tag.outputs.previous-release-tag }} --for-nightly=${{ github.event.inputs.full_release != 'true' }} > new_changelog.md

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.create-tag.outputs.release-name }}
          tag_name: ${{ needs.create-tag.outputs.release-tag }}
          target_commitish: ${{ github.sha }}
          files: release-packages/**/*
          prerelease: ${{ !inputs.full_release }}
          fail_on_unmatched_files: true
          generate_release_notes: false
          body_path: new_changelog.md

      - name: Setup Sentry CLI
        if: inputs.sentry
        uses: mathieu-bour/setup-sentry-cli@v1.3.0
        with:
          version: '2.20.6'
          token: ${{ secrets.SENTRY_TOKEN }}
          organization: zeldaclassic
          project: zc-test
      - name: Finalize sentry
        if: inputs.sentry
        run: |
          sentry-cli --log-level=DEBUG releases set-commits 'zc-test@${{ needs.create-tag.outputs.release-tag }}' --auto
          sentry-cli --log-level=DEBUG releases finalize 'zc-test@${{ needs.create-tag.outputs.release-tag }}'
